"""Create users ,messages,contacts table

Revision ID: 932802a1816d
Revises: 6aa0bdd76003
Create Date: 2024-01-17 06:04:12.597711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932802a1816d'
down_revision = '6aa0bdd76003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
